CREATE TABLE `players` (
   `id` int(11) not null auto_increment,
   `login` varchar(24) not null,
   `haslo` varchar(24) not null,
   `kasa` int(9) not null default '100',
   `level` int(9) not null default '1',
   `exp` int(9) not null default '0',
   `wexp` int(9) not null default '4',
   `skin` int(3) not null default '72',
   `x` double not null,
   `y` double not null,
   `z` double not null,
   `a` double not null,
   `prawko` int(1) not null default '0',
   `pilotaz` int(1) not null default '0',
   `motor` int(1) not null default '0',
   `lickabron` int(1) not null default '0',
   `admin` int(1) not null default '0',
   `vip` int(1) not null default '0',
   `praca` int(1) not null default '0',
   `idf` int(1) not null default '0',
   `ranga` int(4) not null default '0',
   `slot` int(1) not null default '0',
   `slot1` int(2) not null default '0',
   `slot2` int(2) not null default '0',
   `ammo2` int(4) not null default '0',
   `slot3` int(2) not null default '0',
   `ammo3` int(4) not null default '0',
   `slot4` int(2) not null default '0',
   `ammo4` int(4) not null default '0',
   `slot5` int(2) not null default '0',
   `ammo5` int(4) not null default '0',
   `slot6` int(2) not null default '0',
   `ammo6` int(4) not null default '0',
   `slot9` int(2) not null default '0',
   `ammo9` int(4) not null default '0',
   `slot10` int(2) not null default '0',
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE `veh` (
   `id` int(11) not null auto_increment,
   `model` int(3) not null default '401',
   `vx` double not null default '0',
   `vy` double not null default '0',
   `vz` double not null default '0',
   `va` double not null default '0',
   `kolor` smallint(3) not null default '0',
   `kolor2` smallint(3) not null default '1',
   `typ` tinyint(2) not null default '0',
   `fid` smallint(4) not null default '0',
   `cena` int(9) not null default '0',
   `ido` int(9) not null default '0',
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE `org` (
   `id` int(4) not null auto_increment,
   `nazwa` varchar(24) not null,
   `typ` smallint(1) not null default '0',
   `x` double not null default '0',
   `y` double not null default '0',
   `z` double not null default '0',
   `a` double not null default '0',
   `rskin` int(4) not null default '0',
   `rnazwa` varchar(12) not null default 'Brak',
   `rskin2` int(4) not null default '0',
   `rnazwa2` varchar(12) not null default 'brak',
   `rskin3` int(4) not null default '0',
   `rnazwa3` varchar(12) not null default 'brak',
   `rskin4` int(4) not null default '0',
   `rnazwa4` varchar(12) not null default 'brak',
   `rskin5` int(4) not null default '0',
   `rnazwa5` varchar(12) not null default 'brak',
   `rskin6` int(4) not null default '0',
   `rnazwa6` varchar(12) not null default 'brak',
   `rskin7` int(4) not null default '0',
   `rnazwa7` varchar(12) not null default 'brak',
   `rskin8` int(4) not null default '0',
   `rnazwa8` varchar(12) not null default 'brak',
   `rskin9` int(4) not null default '0',
   `rnazwa9` varchar(12) not null default 'brak',
   `rskin10` int(4) not null default '0',
   `rnazwa10` varchar(12) not null default 'brak',
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE `bud` (
   `id` int(4) not null auto_increment,
   `nazwa` varchar(24) not null default 'brak',
   `ex` double not null default '0',
   `ey` double not null default '0',
   `ez` double not null default '0',
   `ea` double not null default '0',
   `eint` int(4) not null default '1',
   `ex2` double not null default '0',
   `ey2` double not null default '0',
   `ez2` double not null default '0',
   `ea2` double not null default '0',
   `eint2` int(4) not null default '1',
   `pickupid` int(10) not null default '0',
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE `biz` (
   `id` int(7) not null auto_increment,
   `nazwa` varchar(24) not null default 'brak',
   `typ` int(4) not null default '0',
   `ex` double not null default '0',
   `ey` double not null default '0',
   `ez` double not null default '0',
   `eint` int(4) not null default '0',
   `ex2` double not null default '0',
   `ey2` double not null default '0',
   `ez2` double not null default '0',
   `eint2` int(4) not null default '0',
   `konto` int(11) not null default '0',
   `produkty` int(11) not null default '100',
   `zamkniety` int(1) not null default '0',
   `pickupid` int(11) not null default '0',
   `idown` int(11) not null default '0',
   `cena` int(11) not null default '100',
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;